### ISSUE TITLE
Keep push-manifest.json as single source of truth

### ISSUE THREAD

**Issue by prateekbh** [vinaypuppal/preact-cli-plugin-netlify#12]
Hi,
This code seems to be duplicated out of preact-cli: https://github.com/vinaypuppal/preact-cli-plugin-netlify/blob/master/index.js#L37-L42

Instead of this, you can just read `push-manifest.json` and convert it to netlify headers. This keeps you away from diverging from the preact-cli changes

**Comment by vinaypuppal** [comment]
Implemented in #14
